### PR TITLE
 Add upstream repository compatibility for debian (version 3.0.x)

### PR DESCRIPTION
**Pull request by gpenaud**
Hi. 

Sorry for the length of the PR. I made my best to keep it simple. Could you merge this ASAP please ? 
Thanks !

### CODE REVIEW

**Comment by gpenaud** [comment]
Do you still maintain the repo? Will you do at long term?

**Comment by dwerder** [comment]
travis-ci tests are failing for Redhat

**Comment by gpenaud** [comment]
I'm fixing it :)

**Comment by dwerder** [comment]
I will merge requests, but I would recommend to use the official Puppetlabs module https://forge.puppetlabs.com/puppetlabs/mongodb

It actively maintained and provides far more functionality.

**Comment by gpenaud** [comment]
This one does not allow to setup multiples mongod instance on same host. That's why I came to yours.
The two last travis-ci errors seem strange to me (Sorry, first time with travis).

**Comment by dwerder** [comment]
Merged and released. Thanks

**Comment by gpenaud** [comment]
Thx to you !

**Pull request merged**
