### PR TITLE
fix $package_name if $repo_manage is set to false

### PR DESCRIPTION
**Pull request by fraenki**
Currently, if `$repo_manage` is set to `false` and the module is used on Debian/Ubuntu, the package name in `install.pp` will resolve to `undef`. This happens because it expects to get the package name from `mongodb::repos::apt`, but this class is not included if `$repo_manage` is set to `false`.

This leads to the following error:

```
Error: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install mongodb-package=3.4.3' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mongodb-package
Error: /Stage[main]/Mongodb::Install/Package[mongodb-package]/ensure: change from purged to 3.4.3 failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold --force-yes install mongodb-package=3.4.3' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package mongodb-package
Notice: /Stage[main]/Mongodb::Install/Anchor[mongodb::install::end]: Dependency Package[mongodb-package] has failures: true
```

Note that `apt` tries to install a package named `mongodb-package`, this is the name of the `Package` resource in `install.pp` rather than the expected package name (because the `name` parameter does not resolve).

My patch fixes this by using `$::mongodb::package_name` if `$repo_manage` is set to `false`.
This also leads to a minor simplification in `install.pp`.

### CODE REVIEW

**Comment by fraenki** [comment]
FWIW, the failed test on Ruby 1.9.x is not related to my patch ;)

```
Gem::InstallError: parallel_tests requires Ruby version >= 2.0.0.
An error occurred while installing parallel_tests (2.14.1), and Bundler cannot continue.
```

**Comment by fraenki** [comment]
Note that a fix for the package name issue was already proposed in #72, but it did not respect that the package name may change, depending on the repository that is used.

**Comment by dwerder** [comment]
I fixed the ruby 1.9.3 problem.
Thanks for PRs

**Comment by dwerder** [comment]
Some tests are failing because of the changes in the old_servicename

**Comment by fraenki** [comment]
@dwerder I've fixed the tests for #85 in #87. Can we git this PR merged too? :)

**Pull request merged**
